### PR TITLE
adding ability to precision precision for shaders

### PR DESCRIPTION
**Pull request by zachkrall**
this is an updated solution for an issue brought up in #15 

with precision added to the constructor, the hydra-editor webpage can now pass whatever the appropriate precision float value should be

newer iOS devices seem to work better with highp but a lot of android devices seem to work best with mediump. By default it will use 'mediump'

example:
```
const Hydra = require('hydra-synth');

const canvas = document.createElement('canvas')

// ... 

let isIOS =
  (/iPad|iPhone|iPod/.test(navigator.platform) ||
    (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)) &&
  !window.MSStream;

let precisionValue = isIOS ? 'highp' : 'mediump';

let hydra = new Hydra({
    canvas: canvas,
    enableStreamCapture: false,
    detectAudio: false,
    // etc
    precision: precisionValue
});
```

☺️✨

### CODE REVIEW

**Comment by zachkrall** [comment]
also, 1) yikes typo in title 2) didn't realize my editor changes all `'` to `"` making this diff larger than it should be 
😞

**Comment by AlexandreRangel** [comment]
Hi @zachkrall ! Great!

How can we add this patch to your Hydra standalone player code?
This will eventually be merged on the main editor too, right?
Thank you!

I put your precision code on this bundle.js but it still doesn't run on iPhone 7:
https://www.alexandrerangel.art.br/hydra/sketch001

**Comment by ojack** [comment]
Hi this is great! Please update to only change relevant code. (not semicolons and quotation marks)...The code is written in standard style js https://standardjs.com/rules.html (for the most part). This makes me think we should include a linter. I also don't have an ios device to test.

@AlexandreRangel what part isn't working on iPhone 7? Any ideas why?

**Comment by AlexandreRangel** [comment]
@ojack , this codes runs on iPad Pro 2017 - but not on the first run. When I refresh the page it runs ok,  and very smooth.
On iPhone 7, it shows either a black or a white screen, even after many refreshes. 
[https://www.alexandrerangel.art.br/hydra/sketch001](https://www.alexandrerangel.art.br/hydra/sketch001)

Almost the same with the Hydra Editor on Glitch:
Runs examples ok on iPad.
Shows just the icons on black background on iPhone 7.

**Comment by zachkrall** [comment]
@ojack 
> But please update to only change relevant code. (not semicolons and quotation marks)

yes definitely, didn't realize it until later

I only have an iPhone X to run it on but maybe I can borrow a phone from someone else.

**Comment by AlexandreRangel** [comment]
@zachkrall I think my latest test didn't use all of your precision patch.
Will wait until the branches get merged to try again. And then the standalone version...

**Comment by zachkrall** [comment]
@ojack corrected the commit history :)

**Comment by ojack** [comment]
Ooops just seeing the update now!

**Pull request merged**
