### PR TITLE
webrtc stream with local signaling server

### PR DESCRIPTION
**Pull request by brucelane**

### CODE REVIEW

**Comment by brucelane** [comment]
before merging, be aware it need a signaling server running a websocket server.
by the way, it uses ws, not socket.io
we shall discuss about it

**Comment by ojack** [comment]
hey i want to figure out how to integrate this with the existing webrtc server / i dont think there is a need for two.

**Comment by brucelane** [comment]
I haven't this part of your code before...

**Comment by brucelane** [comment]
thank you @zachkrall

**Pull request closed without merging**
