### PR TITLE
set regl tex params of a given hydra-source from within init functions

### PR DESCRIPTION
**Pull request by ritchse**
my first PR :P

Pretty self explanatory. Adds min and mag arguments at the end of each init function. If min is specified but mag isn't, mag takes the same value as min. Default is nearest.

Example:

```js
initImage (url = '', min = 'nearest', mag) {
    const img = document.createElement('img')
    img.crossOrigin = 'anonymous'
    img.src = url
    img.onload = () => {
      this.src = img
      this.dynamic = false
      this.tex = this.regl.texture({ data: this.src, min: min, mag: (mag ? mag : min)})
    }
  }
```

Example of use:

```js
s0.initImage('https://i.imgur.com/gcKNCxR.jpg','linear')

src(s0)
  	.scale(3)
	.thresh()
	.out()
```

### CODE REVIEW

**Comment by ojack** [comment]
OOoh nice! In this case I would like to have all parameters other than the URL be passed in as a "texture options" object. 
i.e. 
```javascript
s0.initImage(url, { min: 'nearest', mag: 'linear' }) 
``` 
That way it can change more in the future without big API changes, and also we can support more of the parameters of the REGL texture object, such as wrap and flip, etc. 

Screenshot 2022-01-08 at 11 18 51
s of the REGL texture object:

**Comment by ritchse** [comment]
cool! yh that makes more sense. i'll change the pr to that between today and tomorrow

**Comment by ritchse** [comment]
done !

**Comment by ojack** [comment]
Looks great! I will test and merge in the next few days. Do you have an example usage where you can see the difference between the types of filters?

**Comment by ritchse** [comment]
https://hydra.ojack.xyz/?sketch_id=y8PFtlCrtTxYZ094

```js
//Example of different magnification filters on the same image
//https://github.com/ojack/hydra-synth/pull/102

s0.constructor.prototype.initImage = function (url = '', params) {
    const img = document.createElement('img')
    img.crossOrigin = 'anonymous'
    img.src = url
    img.onload = () => {
      this.src = img
      this.dynamic = false
      this.tex = this.regl.texture({ data: this.src, ...params})
    }
  }

s0.initImage('https://i.imgur.com/Nlp8XO2.jpeg',{ mag: 'nearest'})
s1.initImage('https://i.imgur.com/Nlp8XO2.jpeg',{ mag: 'linear'})
a = (s)=> src(s).scroll(-.35,-.1).scale(4,innerHeight/innerWidth/1.2).thresh()
a(s0).out()
a(s1).out(o1)
src(o0).diff(o1).out(o2)
a(s1).scale(3).out(o3)
render()
fps=1
```

**Comment by ritchse** [comment]
😄

**Pull request merged**
